name: C++ CI

on:
  pull_request

jobs:
  test:
    name: Tests in ${{ matrix.build_type }} with g++
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Release, Debug, RelWithDebInfo]

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && sudo apt install binutils gcc cmake valgrind 

    - name: Build main
      run: CXX=g++ ci-extra/build.sh ${{ matrix.build_type }}

    - name: Test main
      run: ci-extra/test.sh ${{ matrix.build_type }}

    - if: ${{ matrix.build_type == 'RelWithDebInfo' }}
      name: Test main with valgrind
      run: ci-extra/test-valgrind.sh
